""" 
Django settings for blogicum project. 
 
Generated by 'django-admin startproject' using Django 3.2.16. 
 
For more information on this file, see 
https://docs.djangoproject.com/en/3.2/topics/settings/ 
 
For the full list of settings and their values, see 
https://docs.djangoproject.com/en/3.2/ref/settings/ 
 
django_sprint1 
В список INSTALLED_APPS добавлены приложения blog и pages. Назначена переменная 
TEMPLATES_DIR, в которой хранится путь до директории templates. Эта пересенная 
указана в TEMPLATES в значении ключа DIRS. Назначен список STATICFILES_DIRS, 
который хранит путь до директории со статическими файлами. 
 
django_sprint3 
В список INSTALLED_APPS и MIDDLEWARE добавлены debug_toolbar. Назначена 
переменная INTERNAL_IPS для debug_toolbar. Проведена 
локализация(изменеа константа LANGUAGE_CODE = 'ru-RU') 
 
django_sprint4 
Добавлена константа с кастомной моделью пользователя AUTH_USER_MODEL. Подключен 
бэкенд EMAIL константы: EMAIL_BACKEND и путь до дериктории EMAIL_FILE_PATH. 
Добавлены адрес страницы логина LOGIN_URL и LOGIN_REDIRECT_URL. Добавоены 
разрешенные хосты ALLOWED_HOSTS. Установлены и зарегестрированы стили 
django_bootstrap5. Добавлена константа CSRF_FAILURE_VIEW - ошибка проверки CSRF 
(403). Добавлена константа MEDIA_ROOT с путем до папки media. 
""" 
 
from pathlib import Path 
 
# Build paths inside the project like this: BASE_DIR / 'subdir'. 
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-fn41u7c-1z+jwd#dvpeo0m1j-w^s5si#@!*x&4zx-!1!2u@+=h'

DEBUG = True

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'blog:index'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]

CSRF_FAILURE_VIEW = 'pages.views.page_csrf_failure'

EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'

AUTH_USER_MODEL = 'users.MyUser'

MEDIA_ROOT = BASE_DIR / 'media'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pages.apps.PagesConfig',
    'blog.apps.BlogConfig',
    'users.apps.UsersConfig',
    'django_bootstrap5',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

INTERNAL_IPS = [
    '127.0.0.1',
]

ROOT_URLCONF = 'blogicum.urls'

TEMPLATES_DIR = BASE_DIR / 'templates'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blogicum.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ru-RU'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',

    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', 
    }, 
    { 
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', 
    }, 
] 
 
 
# Internationalization 
# https://docs.djangoproject.com/en/3.2/topics/i18n/ 
 
LANGUAGE_CODE = 'ru-RU' 
 
TIME_ZONE = 'UTC' 
 
USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images) 
# https://docs.djangoproject.com/en/3.2/howto/static-files/ 

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
] 

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field 

